server {
    listen      8081;
    server_name  dfa-landing.zilant.tech;
    
    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /404.html;

    location / {
        root /usr/share/nginx/html;
        # try_files $uri /index.html;
    }
}